[8.x.x] Feature/8.x.x develop charts examples
OntimizeWeb/docs pull request #108
Opened 2020-09-11 09:10 UTC by pacogomezimatia

2020-09-14 12:48 UTC, patricia-martinez-imatia commented on _ontimize_web_ngx_charts/configuration/00-overviewchart.md
> +<o-chart type="pie" layout-fill entity="EMovementTypesTotal" x-axis="MOVEMENTTYPES" y-axis="MOVEMENT"></o-chart>
You need to add chat-parametter input in this line

2020-09-14 12:56 UTC, patricia-martinez-imatia commented on _o_faq_posts/07.md
> +blabla
this is incompleted

2020-09-14 13:03 UTC, patricia-martinez-imatia commented on _ontimize_web_ngx_charts/configuration/00-overviewchart.md
> +You can check every *chart parameter* [here](https://nvd3-community.github.io/nvd3/examples/documentation.html).
it would be better to refer to the ontimize-web-chart api because all the options are not implemented

2020-09-14 13:10 UTC, patricia-martinez-imatia commented on _data/components/linebarchart.yml
> +  name: "focusEnable",
focusEnable, focusShowAxisX and focusShowAxisY havent description

2020-09-16 09:20 UTC, manuel-cid commented on _data/components/overviewchart.yml
> +  attributes: ["attr", "service", "service-type", "entity", "query-fallback-function", "query-on-init", "query-on-bind", "pageable", "columns", "keys", "parent-keys", "static-data", "query-method", "
There is some parameters that don't make sense in the chart component like paginated-query-method, insert-method, update-method, delete-method

2020-09-25 14:37 UTC, daniel-grana requested changes

2020-09-25 14:37 UTC, daniel-grana commented on _data/components/linebarchart.yml
> +  path: "charts/overview",
Incorrect path. It would be _"charts/configuration/overview"_
Please review the other configuration files.

2020-10-13 13:57 UTC, merged