[8.x.x] Expandable row documentation
OntimizeWeb/docs pull request #113
Opened 2020-10-02 15:30 UTC by patricia-martinez-imatia

Added expandable row documentation

2020-10-05 05:50 UTC, daniel-grana requested changes

2020-10-05 05:50 UTC, daniel-grana commented on _data/components/otableData/00table.yml
> +  description: "Allow reinitialize table options adding options "
Fix description text, please

2020-10-05 13:52 UTC, daniel-grana approved these changes

2020-10-07 09:04 UTC, manuel-cid commented on _data/components/otableData/11tableRowExpandable.yml
> +  description : "Indicates whether or not to show a expandible column."
Replace `expandible` by `expandable`

2020-10-07 09:04 UTC, manuel-cid commented on _o_components/35-o-table.component.md
> +The `o-table-row-expandable` component enable you to provide additional details about a particular row of table data through expanding or collapsing its content. It's necessary wrap the content of yo
Fix: It's necessary **to** wrap ... template **definition** inside.

2020-10-07 09:04 UTC, manuel-cid commented on _o_components/35-o-table.component.md
> +It is possible to define a *template with context*, so that if the defined template contains a component that extends from `OServiceComponent` class (such as o-table, o-list, o-chart and o-grid), thi
- ... component that extends from `OServiceComponent` class ... -> **from** not necessary
- ... this context can solve functionalities like ... -> this context **provide** functionalities

2020-10-07 09:04 UTC, manuel-cid commented on _o_components/35-o-table.component.md
> +>NOTE: It is necessary define `targets` input and `[data]="row"` to query the data automatically, it will be the references of the components whose query will be launched when expanding the row. The
It is necessary **to** define

2020-10-15 06:44 UTC, manuel-cid approved these changes

2020-10-15 06:44 UTC, manuel-cid commented on _o_components/35-o-table.component.md
> +The `o-table-row-expandable` component enable you to provide additional details about a particular row of table data through expanding or collapsing its content. It's necessary to wrap the content of
Close ng-template tag ``<ng-template let-row></ng-template``

2020-10-23 08:32 UTC, gonzalo-martinez-imt approved these changes

2020-10-23 13:05 UTC, merged