[8.x.x] Develop ontimize-web-ngx-map documentation
OntimizeWeb/docs pull request #180
Opened 2021-03-23 10:11 UTC by pacogomezimatia

2021-03-24 16:18 UTC, patricia-martinez-imatia commented on _ontimize_web_ngx_map/configuration/04-o-geojson-layer.component-api.md
> +permalink: /map/configuration/o-geojson-layer/api
I think this file isnt necessary and this page shout use other layout (without API tab)

2021-03-24 16:45 UTC, manuel-cid requested changes

2021-03-24 16:45 UTC, manuel-cid commented on _ontimize_web_ngx_map/configuration/01-o-map-draw-controls.component.md
> +The component *o-map-draw-controls* is used to show a draw toolbar into the map. You can catch the events triggered with
Is this complete?

2021-03-24 16:45 UTC, manuel-cid commented on _ontimize_web_ngx_map/configuration/04-o-geojson-layer.component.md
> +This is a basic example of a *Map* using the component *o-map-layer* inside to add new WMS layers to the map.
This is the GeoJson layer documentation file but the description is about WMS layers.

2021-03-25 05:39 UTC, daniel-grana requested changes

2021-03-25 05:39 UTC, daniel-grana commented on _data/components/omaplayer.yml
> +  description: "Center the position of the layer",
Explain that the structure is latitude,longitude separated by comma and maybe give an example

2021-03-25 05:39 UTC, daniel-grana commented on _data/components/omarker.yml
> +  description: "Center the position of the layer",
Explain that the structure is latitude,longitude separated by comma

2021-03-25 05:39 UTC, daniel-grana commented on _data/components/omarker.yml
> +  description: "Initial map zoom level.",
This is not the correct definition

2021-03-25 05:39 UTC, daniel-grana commented on _data/components/omarker.yml
> +  description: "Minimum zoom level of the map.",
This is not the correct definition

2021-03-25 05:39 UTC, daniel-grana commented on _data/components/omarker.yml
> +  description: "Maximum zoom level of the map.",
This is not the correct definition

2021-03-25 05:39 UTC, daniel-grana commented on _data/components/omarker.yml
> +  description: "Show or not zoom controls.",
This is not the correct definition

2021-03-25 05:39 UTC, daniel-grana commented on _data/components/omarker.yml
> +  description: "Show or not search control.",
This is not the correct definition

2021-03-25 05:39 UTC, daniel-grana commented on _data/components/omarker.yml
> +  description: "Maximum zoom level of the map.",
It would be useful an example

2021-03-25 05:39 UTC, daniel-grana commented on _data/components/overviewmap.yml
> +  description: "Initialize the map with a given center in latitude and longitude",
Add an example to see how to configure it

2021-03-25 05:39 UTC, daniel-grana commented on _data/components/overviewmap.yml
> +  description: "Defines the array of base layer ids",
Maybe an example would be useful

2021-03-25 05:39 UTC, daniel-grana commented on _data/components/owmslayer.yml
> +
Please check description definitions

2021-04-09 11:12 UTC, merged