[8.x.x] Documentation for combo icon renderer
OntimizeWeb/docs pull request #192
Opened 2021-04-16 09:15 UTC by pacogomezimatia

2021-04-22 08:31 UTC, manuel-cid approved these changes

2021-04-26 13:23 UTC, daniel-grana requested changes

2021-04-26 13:23 UTC, daniel-grana commented on _o_components/02-o-combo.component.md
> +  <o-combo-renderer-icon icon-position="right" icon-column="materialIcon"></o-combo-renderer-percentage>
I think it is necessary to change this example. I cannot see _materialIcon_ column defined in _columns_ attribute. And for better comprehension I think it should be great by using more real column names into configuration instead _key_ and _value_

2021-04-27 08:44 UTC, daniel-grana approved these changes

2021-04-29 15:35 UTC, patricia-martinez-imatia approved these changes

2021-05-03 07:01 UTC, gonzalo-martinez-imt approved these changes

2021-05-07 13:00 UTC, merged