[8.x.x] Form Layout Manager new split-pane mode and Form docs updated
OntimizeWeb/docs pull request #196
Opened 2021-05-19 14:43 UTC by gonzalo-martinez-imt

2021-05-21 15:05 UTC, daniel-grana requested changes

2021-05-21 15:05 UTC, daniel-grana commented on _o_components/57-o-form-layout-manager.component.md
> +    <o-form-layout-tabgroup-options color="accent" title="CUSTOMERS"
-tab-group-??? Here should be _o-form-layout-split-pane-options_

2021-06-21 15:53 UTC, gonzalo-martinez-imt commented on _o_components/57-o-form-layout-manager.component.md
> +    <o-form-layout-tabgroup-options color="accent" title="CUSTOMERS"
This is a different example

2021-06-21 15:58 UTC, daniel-grana approved these changes

2021-06-21 15:59 UTC, merged