[8.x.x] Add note to quick-filter about filter-case-sensitive and pageable
OntimizeWeb/docs pull request #197
Opened 2021-05-24 11:02 UTC by pacogomezimatia

2021-05-24 11:25 UTC, daniel-grana requested changes

2021-05-24 11:25 UTC, daniel-grana commented on _o_components/35-o-table.component.md
> +
Put it in a NOTE to highlight this info

2021-05-24 13:06 UTC, daniel-grana approved these changes

2021-05-25 12:12 UTC, manuel-cid approved these changes

2021-05-25 14:15 UTC, patricia-martinez-imatia approved these changes

2021-05-25 14:17 UTC, gonzalo-martinez-imt approved these changes

2021-05-26 08:00 UTC, merged