[8.x.x] Filter column active by default
OntimizeWeb/docs pull request #322
Opened 2022-08-25 07:52 UTC by tomfacal

2022-08-26 06:13 UTC, daniel-grana requested changes

2022-08-26 06:13 UTC, daniel-grana commented on _o_components/35-o-table.component.md
> +- Using the input columns of the component `o-table-columns-filter`, adding the columns separated by ‘;’.
```suggestion
- Using the input `columns` of the component `o-table-columns-filter`, adding the columns separated by ‘;’.
```

2022-08-26 06:17 UTC, daniel-grana approved these changes

2022-08-29 11:28 UTC, patricia-martinez-imatia approved these changes

2022-08-30 07:30 UTC, merged