New input `disable-selection-function`
OntimizeWeb/docs pull request #352
Opened 2022-12-15 12:50 UTC by patricia-martinez-imatia

2022-12-15 12:53 UTC, tomfacal submitted a review, later dismissed

2022-12-15 12:59 UTC, daniel-grana requested changes

2022-12-15 12:59 UTC, daniel-grana commented on _o_components/35-o-table.component.md
> +Additionally, you can specify a function setting the input `disable-selection-function` to disable the checkboxes.
```suggestion
Additionally, you can specify a function setting the input `disable-selection-function` to disable the checkboxes depending on a condition. This function receives full data record for allowing you to enable/disable selection checkbox depending on value/s of the record.
```

2022-12-15 12:59 UTC, daniel-grana commented on _data/components/otableData/00table.yml
> +  description: "Function that will be used to disable the enable/disable state of the checkboxes of the rows."
```suggestion
  description: "Function that will be used to allow row selection by changing the enable/disable state of the checkboxes of the rows."
```

2022-12-16 08:57 UTC, daniel-grana approved these changes

2022-12-16 12:08 UTC, tomfacal approved these changes

2022-12-19 12:16 UTC, merged