Documentation about new sql-type `UUID`
OntimizeWeb/docs pull request #386
Opened 2023-05-03 17:40 UTC by patricia-martinez-imatia

2023-05-04 07:02 UTC, daniel-grana requested changes

2023-05-04 07:02 UTC, daniel-grana commented on _o_components/09-o-list-picker.component.md
> +Ontimize web now supports the JDBC **UUID** sql type. To indicate that a combo column is of type UUID, all you have to do is to set `sql-type="UUID"`  in the `o-combo` component as indicated in the f
```suggestion
Ontimize web now supports the JDBC **UUID** sql type. To indicate that a combo column is of type UUID, all you have to do is to set `sql-type="UUID"`  in the `o-list-picker` component as indicated in the following example.
```

2023-05-04 10:30 UTC, javierFernandezMendez approved these changes, later dismissed

2023-05-04 11:32 UTC, daniel-grana approved these changes, later dismissed

2023-05-05 12:55 UTC, daniel-grana approved these changes

2023-05-05 12:56 UTC, javierFernandezMendez approved these changes

2023-05-05 12:56 UTC, merged