Typography errors fix
OntimizeWeb/docs pull request #400
Opened 2023-06-27 08:18 UTC by javierFernandezMendez

2023-07-03 14:26 UTC, patricia-martinez-imatia requested changes

2023-07-03 14:26 UTC, patricia-martinez-imatia commented on _data/components/grid.yml
> +  type: "boolean",
```suggestion
  type: "string",
```

2023-07-04 08:59 UTC, daniel-grana approved these changes

2023-07-04 09:20 UTC, patricia-martinez-imatia approved these changes

2023-07-04 11:43 UTC, tomfacal approved these changes

2023-07-05 05:04 UTC, merged