Documentation filemanager s3
OntimizeWeb/docs pull request #402
Opened 2023-06-29 12:10 UTC by javierFernandezMendez

2023-07-03 10:01 UTC, daniel-grana approved these changes, later dismissed

2023-07-03 14:56 UTC, patricia-martinez-imatia requested changes

2023-07-03 14:56 UTC, patricia-martinez-imatia commented on _ontimize_web_ngx_filemanager/services/00-filemanager.md
>  title: "File Manager Service"
```suggestion
title: "File Manager DMS Service"
```

2023-07-03 14:56 UTC, patricia-martinez-imatia commented on _ontimize_web_ngx_filemanager/services/01-filemanager-sdms.md
> +title: "File Manager Service"
```suggestion
title: "File Manager SDMS Service"
```

2023-07-03 14:56 UTC, patricia-martinez-imatia commented on _ontimize_web_ngx_filemanager/general/02-installation.md
> +If you want to use the SDMS file manager engine you need to add the `type` attribute to yours `o-filemanager-table` component. Also you can define your own workspace as the example bellow.
```suggestion
If you want to use the SDMS file manager engine you need to add the `type='S3'` attribute to yours `o-filemanager-table` component. 

Also you must indicate also the form column name that stores the work space identifier in the workspace-key attribute or define the `workspace-S3` function as the example bellow
```

2023-07-03 14:56 UTC, patricia-martinez-imatia commented on _ontimize_web_ngx_filemanager/general/02-installation.md
> +`cutomers-home.html`:
```suggestion
`customers-detail.component.html`:
```

2023-07-03 14:56 UTC, patricia-martinez-imatia commented on _ontimize_web_ngx_filemanager/general/02-installation.md
> +`customers-home.ts`:
```suggestion
`customers-detail.component.ts`:
```

2023-07-03 14:56 UTC, patricia-martinez-imatia commented on _ontimize_web_ngx_filemanager/general/02-installation.md
> +<o-filemanager-table type="S3" service="customers" workspace-key="ID_DMS_DOC" workspaceS3="setWorkspaceS3(form.data)"></o-filemanager-table>
```suggestion
<o-filemanager-table type="S3" service="customers" [workspace-s3]="setWorkspaceS3"></o-filemanager-table>
```

2023-07-03 14:56 UTC, patricia-martinez-imatia commented on _ontimize_web_ngx_filemanager/general/02-installation.md
> +    return { name: 'default', data: { id: [1] } };
```suggestion
    return { name: 'default', data: { id: data['CUSTOMERID'] } };
```

2023-07-03 14:56 UTC, patricia-martinez-imatia commented on _ontimize_web_ngx_filemanager/services/01-filemanager-sdms.md
> +Configure de Ontimize Web File Manager service.
```suggestion
Configure de Ontimize Web File Manager SDMS Service.
```

2023-07-04 08:58 UTC, daniel-grana submitted a review, later dismissed

2023-07-04 09:32 UTC, patricia-martinez-imatia requested changes

2023-07-04 09:32 UTC, patricia-martinez-imatia commented on _ontimize_web_ngx_filemanager/services/00-filemanager.md
>  import { FileManagerService } from 'ontimize-web-ngx-filemanager';
```suggestion
import { FileManagerOntimizeService } from 'ontimize-web-ngx-filemanager';
```

2023-07-04 09:32 UTC, patricia-martinez-imatia commented on _ontimize_web_ngx_filemanager/services/01-filemanager-sdms.md
> +import { FileManagerService } from 'ontimize-web-ngx-filemanager';
```suggestion
import { FileManagerS3Service } from 'ontimize-web-ngx-filemanager';
```

2023-07-04 09:32 UTC, patricia-martinez-imatia commented on _ontimize_web_ngx_filemanager/services/01-filemanager-sdms.md
> +In this section we describe the REST API used by the `FileManagerService`.
```suggestion
In this section we describe the REST API used by the `FileManagerS3Service `.
```

2023-07-05 08:16 UTC, daniel-grana approved these changes

2023-07-05 08:22 UTC, patricia-martinez-imatia approved these changes

2023-07-05 08:23 UTC, merged