Extending permissions documentation
OntimizeWeb/docs pull request #409
Opened 2023-07-17 06:23 UTC by javierFernandezMendez

2023-07-18 05:17 UTC, patricia-martinez-imatia requested changes

2023-07-18 05:17 UTC, patricia-martinez-imatia commented on _docs/15c-permissions-example.md
> +In case we wanna change the permission service we need to do two steps:
```suggestion
In case we want to change the permission service we need to do two steps:
```
wanna is is informal

2023-07-18 05:17 UTC, patricia-martinez-imatia commented on _docs/15c-permissions-example.md
> +...
I think you can write a small example by overriding the loadPermission and configureService methods

2023-07-18 05:17 UTC, patricia-martinez-imatia commented on _docs/15c-permissions-example.md
> +Other important configuration it's to define on the `main-routing.module.ts` the `canActivateChild` parameter to manage the routes permissions.
I think it's a good idea that the example includes restrictPermissionsRedirect: '403' and a screen with the redirect

2023-07-20 09:34 UTC, daniel-grana submitted a review, later dismissed

2023-07-20 09:43 UTC, patricia-martinez-imatia requested changes

2023-07-20 09:43 UTC, patricia-martinez-imatia commented on _docs/15c-permissions-example.md
>  First file we need to configure on our frontend it's the `app.config.ts`, inside we need to define the type of permission we wanna use (see [here](https://ontimizeweb.github.io/docs/v8/guide/appconfi
```suggestion
First file we need to configure on our frontend it's the `app.config.ts`, inside we need to define the type of permission we want to use (see [here](https://ontimizeweb.github.io/docs/v8/guide/appconfig/#permissions-configuration){:target="_blank"} for the different types) and the service used to get the server permissions.
```

2023-07-20 09:51 UTC, patricia-martinez-imatia requested changes

2023-07-20 09:51 UTC, patricia-martinez-imatia commented on _docs/15c-permissions-example.md
> +The last configuration that we can do it's to define a redirection page to visit when the user dont have permissions to access the page requested. To configure this page you need to add the route (or
```suggestion
The last configuration that we can do it's to define a redirection page to visit when the user does not have permissions to access the page requested. To configure this page you need to add the route (or use the ontimize component `403`) to the `restrictedPermissionsRedirect` parameter on the routing module of the component. Example:
```

2023-07-20 15:35 UTC, patricia-martinez-imatia requested changes

2023-07-20 15:35 UTC, patricia-martinez-imatia commented on _docs/15c-permissions-example.md
> +First file we need to configure on our frontend it's the `app.config.ts`, inside we need to define the type of permission we want to use (see [here](https://ontimizeweb.github.io/docs/v8/guide/appcon
```suggestion
First file we need to configure on our frontend it’s the `app.config.ts` and add `permissionsServiceType` and `permissionsConfiguration` object. In `permissionsServiceType`, you define the type of permission to use (*OntimizeEEPermissions* or *OntimizePermissions*, for more information see [here]({{ base_path }}/guide/appconfig/#permissions-configuration){:target="_blank"}) and `permissionsConfiguration` which should contain the permissions service whose path should be defined in `app.services.config.ts` (defined in the following code section of this page).
```

2023-07-20 15:35 UTC, patricia-martinez-imatia commented on _docs/15c-permissions-example.md
> +...
In this example, it would be a good idea to write an example with restricted permission on a specific module and screen as CandidatesNewComponent

2023-07-21 11:57 UTC, patricia-martinez-imatia approved these changes

2023-07-21 12:02 UTC, daniel-grana approved these changes

2023-07-21 12:03 UTC, merged