Updated old version images
OntimizeWeb/docs pull request #529
Opened 2024-02-20 07:23 UTC by javierFernandezMendez

2024-02-20 09:10 UTC, patricia-martinez-imatia requested changes

2024-02-20 09:10 UTC, patricia-martinez-imatia commented on assets/images/layouts/app-layout/card-menu-layout.png
It would be very nice if the screenshot of the card menu also had the graphics that were in the old image to give visibility to the functionality of the cards layout

2024-02-20 09:10 UTC, patricia-martinez-imatia commented on assets/images/components/card-menu-item/example.PNG
It would be very nice if the card menu screenshot also had the demarcation (dotted line) of the card content that is customizable

2024-02-20 09:10 UTC, patricia-martinez-imatia commented on assets/images/components/inputs/o-combo-multiple-trigger-label.png
1. It would be great if the active and inactive status were displayed like the previous image. 
2. Also try to make the images not so wide
3. Check the width of the other images

2024-02-20 09:10 UTC, patricia-martinez-imatia commented on assets/images/components/inputs/slider/o-slider-vertical-tickinterval.png
Add screenshot with tick interval

2024-02-20 09:10 UTC, patricia-martinez-imatia commented on assets/images/components/list/add-content-toolbar-position-start.png
Add an example where a combo is added to the beginning of the toolbar like the previous example

2024-02-20 09:10 UTC, patricia-martinez-imatia commented on assets/images/components/list/add-content-toolbar-position-start2.png
Add an example where a combo and a buttom  are added to the beginning of the toolbar like the previous example

2024-02-20 09:10 UTC, patricia-martinez-imatia commented on assets/images/components/list/add-content-toolbar.png
Add an example where a combo is added to the beginning  of the toolbar abd a toglle to the ending like the previous example

2024-02-20 09:10 UTC, patricia-martinez-imatia commented on assets/images/components/menu/o-bar-menu.png
The screenshot does not correspond to the bar menu

2024-02-20 09:10 UTC, patricia-martinez-imatia commented on assets/images/components/tabla/add-content-toolbar.png
Add an example where a combo is added to the beginning of the toolbar and a toggle to the ending like the previous example

2024-02-20 09:10 UTC, patricia-martinez-imatia commented on assets/images/components/tabla/custom-selectall.png
keep the previous screenshot

2024-02-20 09:10 UTC, patricia-martinez-imatia commented on assets/images/components/tabla/customization.png
In this example the background of the table title is not customized

2024-02-20 09:14 UTC, patricia-martinez-imatia submitted a review, later dismissed

2024-02-20 09:14 UTC, patricia-martinez-imatia commented on assets/images/layouts/form-container/customers_fixed_withoutbreadcrumb.gif
The screen should be without breadcrumb?

2024-02-20 09:14 UTC, patricia-martinez-imatia commented on assets/images/layouts/app-layout/custom_user_info.png
This screenshot should reflect the change indicated in the documentation

2024-02-21 10:47 UTC, javierFernandezMendez commented on assets/images/layouts/app-layout/card-menu-layout.png
There is a section with the custom card layout.

2024-02-21 18:09 UTC, daniel-grana approved these changes

2024-02-22 08:20 UTC, merged