Created directive tree
OntimizeWeb/docs pull request #618
Opened 2024-06-07 12:57 UTC by javier-fernandez-imatia

2024-06-10 13:16 UTC, patricia-martinez-imatia requested changes

2024-06-10 13:16 UTC, patricia-martinez-imatia commented on _includes/o-component-table.md
> +          <li data-jstree='{"opened":true, "icon":"{{ base_path }}/assets/jstree/html.png"}'>o-table-cell-renderer-action</li>
all render and editor are going inside o-table-column

2024-06-10 13:16 UTC, patricia-martinez-imatia commented on _includes/o-component-table.md
> +          <li data-jstree='{"opened":true, "icon":"{{ base_path }}/assets/jstree/html.png"}'>o-table-columns-filter-column</li>
goto inside o-table-columns-filter

2024-06-10 15:07 UTC, patricia-martinez-imatia submitted a review, later dismissed
Check o-component-single.md, the algorithm is not correct because it is always at one level in the hierarchy

![image](https://github.com/OntimizeWeb/docs/assets/32088627/36e820c8-34f0-4090-9c15-bcfec2ec20f5)

2024-06-12 07:01 UTC, daniel-grana submitted a review, later dismissed

2024-06-13 10:22 UTC, daniel-grana approved these changes

2024-06-13 12:50 UTC, merged