Added main title and API title changed
OntimizeWeb/docs pull request #621
Opened 2024-06-13 12:00 UTC by javier-fernandez-imatia

2024-06-13 12:42 UTC, daniel-grana approved these changes, later dismissed

2024-06-13 12:54 UTC, patricia-martinez-imatia requested changes

2024-06-13 12:54 UTC, patricia-martinez-imatia commented on _data/components/textInput.yml
> +apiTitle: "OtextInputComponent"
```suggestion
apiTitle: "OTextInputComponent"
```

2024-06-17 08:18 UTC, daniel-grana approved these changes

2024-06-18 07:42 UTC, patricia-martinez-imatia approved these changes

2024-06-18 08:10 UTC, merged