Change CRUD methods on services
OntimizeWeb/docs pull request #77
Opened 2020-07-16 11:22 UTC by pacogomezimatia

2020-07-17 07:50 UTC, manuel-cid commented on _docs/15-service.md
> +import { ServiceResponse } from '../../interfaces/service-response.interface';
`ServiceResponse` should be imported from ontimize-web-ngx

2020-07-17 07:50 UTC, manuel-cid requested changes
See comments

2020-07-17 07:54 UTC, manuel-cid approved these changes

2020-07-20 12:42 UTC, daniel-grana approved these changes

2020-07-20 12:54 UTC, patricia-martinez-imatia approved these changes

2020-07-21 07:23 UTC, merged